# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Miguel Xavier Penha Neto
email: miguelxpn2@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Blog about programming and nerdy stuff.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.miguelxpn.com" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  miguelxpn

plainwhite:
  name: Miguel Xavier Penha Neto
  tagline: Developer, Hacker.
  date_format: "%b %-d, %Y"
  sitemap: true
  analytics_id: "UA-72191596-1"
  portfolio_image:  "assets/portfolio.png"

  social_links:
    github: miguelxpn
    linkedIn: in/miguel-xavier-penha-neto-ba583a174

# Build settings
remote_theme: thelehhman/plainwhite-jekyll
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
